# Generated by Django 5.1.4 on 2025-01-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Name of the administrator (e.g., Principal, Dean, etc.)', max_length=100)),
                ('position', models.CharField(help_text='Position or role (e.g., Principal, Vice Principal)', max_length=100)),
                ('description', models.TextField(help_text='Description of responsibilities or role')),
                ('image', models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='administration_images/')),
            ],
        ),
    ]
