# Generated by Django 5.1.4 on 2025-01-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course_name', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('examination_body', models.CharField(choices=[('KNEC', 'KNEC'), ('CDACC', 'CDACC'), ('KASNEB', 'KASNEB')], max_length=10)),
                ('course_level', models.CharField(choices=[('Level 6', 'Level 6'), ('Level 5', 'Level 5'), ('Level 4', 'Level 4'), ('Level 3', 'Level 3'), ('Short courses', 'Short courses'), ('Accounting', 'Accounting'), ('NITA', 'NITA')], max_length=20)),
            ],
        ),
    ]
