# Generated by Django 5.1.4 on 2025-01-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
