# Generated by Django 5.1.4 on 2025-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0003_remove_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Artisan', 'Artisan'), ('Short courses', 'Short courses'), ('Accounting', 'Accounting'), ('NITA', 'NITA')], max_length=20),
        ),
    ]
