# Generated by Django 5.1.4 on 2025-01-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0005_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='link',
        ),
        migrations.AddField(
            model_name='notice',
            name='uploadNotice',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
