# Generated by Django 5.1.4 on 2025-01-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0006_remove_notice_link_notice_uploadnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='department_images/')),
                ('description', models.TextField()),
                ('hod_name', models.CharField(max_length=150)),
                ('hod_message', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='mwala_app.course')),
            ],
        ),
    ]
