# Generated by Django 5.1.4 on 2025-01-06 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0007_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='mwala_app.course'),
        ),
    ]
