# Generated by Django 5.1.4 on 2025-01-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0008_alter_department_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mwala_app.department'),
            preserve_default=False,
        ),
    ]
