# Generated by Django 5.1.4 on 2025-01-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0010_supportingdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('deadlineDate', models.DateField()),
                ('uploadNotice', models.FileField(blank=True, null=True, upload_to='notices/')),
            ],
        ),
    ]
