# Generated by Django 5.1.4 on 2025-01-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0011_jobsvacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsvacancies',
            name='uploadNotice',
            field=models.FileField(blank=True, null=True, upload_to='Jobs_vacancies/'),
        ),
    ]
