# Generated by Django 5.1.4 on 2025-01-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0012_alter_jobsvacancies_uploadnotice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsvacancies',
            old_name='uploadNotice',
            new_name='uploadJobs',
        ),
    ]
