# Generated by Django 5.1.4 on 2025-01-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0014_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news/images/')),
                ('video_attachment', models.FileField(blank=True, null=True, upload_to='news/videos/')),
                ('date', models.DateField()),
            ],
        ),
    ]
