# Generated by Django 5.1.4 on 2025-01-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0015_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(max_length=1200)),
            ],
        ),
    ]
