# Generated by Django 5.1.4 on 2025-01-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0017_contact_alter_studentaffairs_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('departments', models.CharField(max_length=255)),
                ('service_rating', models.CharField(max_length=50)),
                ('complaints', models.CharField(max_length=3)),
                ('complaints_description', models.TextField(blank=True, null=True)),
                ('compliments', models.CharField(max_length=3)),
                ('compliments_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
