# Generated by Django 5.1.4 on 2025-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0019_rename_departments_feedback_department_choices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('kcse_grade', models.CharField(max_length=5)),
                ('course', models.CharField(max_length=100)),
                ('intake_month', models.CharField(max_length=20)),
                ('kcse_certificate', models.FileField(upload_to='kcse_certificates/')),
                ('birth_certificate', models.FileField(upload_to='birth_certificates/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
