# Generated by Django 5.1.4 on 2025-01-15 05:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0022_studentaffairs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Description of responsibilities or role'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod_message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='studentaffairs',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='supportingdepartment',
            name='hod_message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
