# Generated by Django 5.1.4 on 2025-01-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0024_alter_course_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='county',
            field=models.CharField(default='Nairobi', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mwala_app.department'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mwala_app.course'),
        ),
    ]
