# Generated by Django 5.1.4 on 2025-01-20 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0027_alter_studentaffairs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
