# Generated by Django 5.1.4 on 2025-01-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0029_tenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod_image',
            field=models.ImageField(blank=True, null=True, upload_to='hod_images/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
