# Generated by Django 5.1.4 on 2025-01-29 12:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0030_department_hod_image_alter_department_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MwalaBrachures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
