# Generated by Django 5.1.4 on 2025-01-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0031_mwalabrachures'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwalabrachures',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mwalabrachures',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochure/'),
        ),
    ]
