# Generated by Django 5.1.4 on 2025-02-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0033_brochures_delete_mwalabrachures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdepartment',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
