# Generated by Django 5.1.4 on 2025-02-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0034_alter_supportingdepartment_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Diploma(level 6)', 'Diploma(level 6)'), ('Certificate(level 5)', 'Certificate(level 5)'), ('Artisan(level 4)', 'Artisan(level 4)'), ('Short Courses(level 3)', 'Short Courses(level 3)'), ('Accounting', 'Accounting'), ('NITA', 'NITA')], max_length=200),
        ),
    ]
