# Generated by Django 5.1.4 on 2025-05-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0036_department_hod_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='position_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
