# Generated by Django 5.1.4 on 2025-06-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0037_administration_position_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdepartment',
            name='hod_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
