# Generated by Django 5.1.4 on 2025-06-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0038_supportingdepartment_hod_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdepartment',
            name='hod_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
