# Generated by Django 5.1.4 on 2025-06-12 21:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0039_alter_supportingdepartment_hod_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportingdepartment',
            name='hod_info',
        ),
        migrations.AddField(
            model_name='supportingdepartment',
            name='hod_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1200, null=True),
        ),
    ]
