# Generated by Django 5.1.4 on 2025-06-12 21:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwala_app', '0040_remove_supportingdepartment_hod_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name='supportingdepartment',
            name='hod_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=12000, null=True),
        ),
    ]
